### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [vitkabele/complete-mac#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by vitkabele** [comment]
Thanks!  The MIT license should work just fine right?

**Comment by unixorn** [comment]
MIT is a good choice. For the purposes of the list, I only care that there be _a_ license that the users can see when they go to your repo so they can decide if they're able to use it. :-)
